Update lib.py
siznax/moo pull request #20
Opened 2021-03-02 04:41 UTC by khafrewatkins

Here are the changes you requested.  Please let me know any corrections or additional alterations need to be made.  I commented out the affected code blocks and adjustments. I know github tracks changes but just to make it more visible.

2021-03-02 17:32 UTC, siznax commented
Thanks for the PR @khafrewatkins! :partying_face:

You commented out ``lib.albums()`` (note the "s" on the end—sorry, that's confusing), but we want to leave that function the way it is—so you can _comment_ it back in.

You commented out ``lib.album()`` which is what we want. That function is not being used, and is too close to ``lib.albums()``. So, go ahead and _delete_ that function in your PR code. Don't worry, none of this code will be merged until we're ready.

You changed ``lib.info()`` to ``lib.album()`` which is what I asked for. However, now I see that having ``albums()`` and ``album()`` is confusing. Let's change ``lib.info()``  to ``lib.album_info()`` instead.

If you're still up for it, just make those changes on your PR branch, commit, and push them. They should show up here for us to continue working with.

2021-03-02 17:41 UTC, siznax requested changes
Thanks for the PR @khafrewatkins! :partying_face:

You commented out ``lib.albums()`` (note the "s" on the end—sorry, that's confusing), but we want to leave that function the way it is—so you can _comment_ it back in.

You commented out ``lib.album()`` which is what we want. That function is not being used, and is too close to ``lib.albums()``. So, go ahead and _delete_ that function in your PR code. Don't worry, none of this code will be merged until we're ready.

You changed ``lib.info()`` to ``lib.album()`` which is what I asked for. However, now I see that having ``albums()`` and ``album()`` is confusing. Let's change ``lib.info()``  to ``lib.album_info()`` instead.

If you're still up for it, just make those changes on your PR branch, commit, and push them. They should show up here for us to continue working with.

2021-03-02 17:52 UTC, siznax requested changes

2021-03-02 17:52 UTC, siznax commented on Moo/play/lib.py
> +#     return out
You commented out lib.albums() (note the "s" on the end—sorry, that's confusing), but we want to leave that function the way it is—so you can comment it back in.

2021-03-02 17:52 UTC, siznax commented on Moo/play/lib.py
> +#             return str(path)
You commented out lib.album() which is what we want. That function is not being used, and is too close to lib.albums(). So, go ahead and delete that function. Don't worry, none of this code will be merged until we're ready.

2021-03-02 17:52 UTC, siznax commented on Moo/play/lib.py
> +    Changed def info to def album()
You changed lib.info() to lib.album() which is what I asked for. However, now I see that having albums() and album() is confusing. Let's change lib.info() to lib.album_info() instead.

2021-03-02 18:31 UTC, khafrewatkins commented
Oh okay got it!  I will make those changes.

On Tue, Mar 2, 2021, 11:33 AM Steve <notifications@github.com> wrote:

> Thanks for the PR @khafrewatkins <https://github.com/khafrewatkins>! 🥳
>
> You commented out lib.albums() (note the "s" on the end—sorry, that's
> confusing), but we want to leave that function the way it is—so you can
> *comment* it back in.
>
> You commented out lib.album() which is what we want. That function is not
> being used, and is too close to lib.albums(). So, go ahead and *delete*
> that function in your PR code. Don't worry, none of this code will be
> merged until we're ready.
>
> You changed lib.info() to lib.album() which is what I asked for. However,
> now I see that having albums() and album() is confusing. Let's change
> lib.info() to lib.album_info() instead.
>
> If you're still up for it, just make those changes on your PR branch,
> commit, and push them. They should show up here for us to continue working
> with.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/siznax/moo/pull/20#issuecomment-789080667>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHF2ONG2CQ4PUY34FGGVA53TBUOM7ANCNFSM4YN72CUA>
> .
>

2021-03-02 23:30 UTC, siznax requested changes
Looking good, but we need to keep code change comments out of docstrings. Use the ``-m <msg>`` option for that when you commit. See our project's commit history for examples: https://github.com/siznax/moo/commits/main

2021-03-02 23:30 UTC, siznax commented on Moo/play/lib.py
> +    '''
This is  a [docstring](https://www.python.org/dev/peps/pep-0257/) which should not be used for code comments. Let's remove "Removing/Erasing" here.

2021-03-02 23:30 UTC, siznax commented on Moo/play/lib.py
> +def album_info(track, metadata):
Perfect.

2021-03-02 23:30 UTC, siznax commented on Moo/play/lib.py
> +    Changed def info to def album_info()
Please remove this from the docstring. Git will show us this change. Comments like this should be added as a [``-m <msg>``](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--mltmsggt) to your commit.

2021-03-03 04:25 UTC, khafrewatkins commented
Ahhh okay.  I will do that know thanks for guiding a newb through this.

On Tue, Mar 2, 2021 at 5:31 PM Steve <notifications@github.com> wrote:

> *@siznax* requested changes on this pull request.
>
> Looking good, but we need to keep code change comments out of docstrings.
> Use the -m <msg> option for that when you commit. See our project's
> commit history for examples: https://github.com/siznax/moo/commits/main
> ------------------------------
>
> In Moo/play/lib.py
> <https://github.com/siznax/moo/pull/20#discussion_r585986715>:
>
> > +    ''' Removing/Erasing
> +    returns dict of minimal album metadata
> +    '''
>
> This is a docstring <https://www.python.org/dev/peps/pep-0257/> which
> should not be used for code comments. Let's remove "Removing/Erasing" here.
> ------------------------------
>
> In Moo/play/lib.py
> <https://github.com/siznax/moo/pull/20#discussion_r585987028>:
>
> > @@ -354,9 +347,9 @@ def index(config, sort=None):
>      return sorted(albums, key=sort_key, reverse=True)
>
>
> -def album(track, metadata):
> +def album_info(track, metadata):
>
> Perfect.
> ------------------------------
>
> In Moo/play/lib.py
> <https://github.com/siznax/moo/pull/20#discussion_r585987998>:
>
> >      '''
> -    Changed def info to def album()
> +    Changed def info to def album_info()
>
> Please remove this from the docstring. Git will show us this change.
> Comments like this should be added as a -m <msg>
> <https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--mltmsggt>
> to your commit.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/siznax/moo/pull/20#pullrequestreview-602367472>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHF2ONAZTDZBCPEHK2L42C3TBVYLNANCNFSM4YN72CUA>
> .
>

2021-03-03 16:28 UTC, siznax commented
Thanks for your help @khafrewatkins. It looks like we lost the entire docstring from ``lib.albums()``. We'll have to restore that. I can't merge this pull request at this point, because it will break the main branch. Once I start developing unit tests, that will be apparent in GitHub.

Remember, there is no such thing as a "newbie" because no one can know everything. We all have something to learn _from each other_.

Let me know if you want to continue working on this. We need to satisfy all of [#15] in order to merge.

2021-03-03 17:35 UTC, khafrewatkins commented
Yes I will do whatever needs to be done!

On Wed, Mar 3, 2021, 10:29 AM Steve <notifications@github.com> wrote:

> Thanks for your help @khafrewatkins <https://github.com/khafrewatkins>.
> It looks like we lost the entire docstring from lib.albums(). We'll have
> to restore that. I can't merge this pull request at this point, because it
> will break the main branch. Once I start developing unit tests, that will
> be apparent in GitHub.
>
> Remember, there is no such thing as a "newbie" because no one can know
> everything. We all have something to learn *from each other*.
>
> Let me know if you want to continue working on this. We need to satisfy
> all of [#15 <https://github.com/siznax/moo/issues/15>] in order to merge.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/siznax/moo/pull/20#issuecomment-789847072>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHF2ONDJUUS4YWZXH53TGGLTBZPVTANCNFSM4YN72CUA>
> .
>

2021-03-03 19:15 UTC, siznax requested changes

2021-03-03 19:15 UTC, siznax commented on Moo/play/lib.py
> +    ''' Removing/Erasing
Please remove "Removing/Erasing" but leave the docstring.

2021-03-12 20:08 UTC, siznax approved these changes

2021-03-12 20:08 UTC, merged

2021-03-12 20:09 UTC, siznax commented
Thanks for your help @khafrewatkins!